// src/app/components/analytics/analytics.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subscription, interval } from 'rxjs';
import { AlertsStoreService } from '../../services/alerts-store.service';
import { StatsCardsComponent } from '../stats-cards/stats-cards.component';

@Component({
  selector: 'app-analytics',
  standalone: true,
  imports: [CommonModule, StatsCardsComponent],
  templateUrl: './analytics.component.html',
  styleUrls: ['./analytics.component.css']
})
export class AnalyticsComponent implements OnInit, OnDestroy {
  private subscriptions = new Subscription();

  constructor(private alertsStore: AlertsStoreService) {}

  ngOnInit(): void {
    this.alertsStore.fetchAlerts();

    this.subscriptions.add(
      interval(5000).subscribe(() => {
        this.alertsStore.fetchAlerts();
      })
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.unsubscribe();
  }
}

<div class="analytics">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <div>
      <h2 class="mb-1">
        <i class="bi bi-bar-chart-line me-2"></i>
        Analytics
      </h2>
      <p class="text-muted mb-0">Overview of alert statistics and status counts</p>
    </div>
  </div>

  <!-- Stats Cards (reusable component — analytics mode with extra cards) -->
  <app-stats-cards mode="analytics"></app-stats-cards>
</div>

// src/views/Analytics.vue
<template>
  <div class="analytics">
    <div class="d-flex justify-content-between align-items-center mb-4">
      <div>
        <h2 class="mb-1">
          <i class="bi bi-bar-chart-line me-2"></i>
          Analytics
        </h2>
        <p class="text-muted mb-0">Overview of alert statistics and status counts</p>
      </div>
    </div>

    <!-- Stats Cards (reusable component) -->
    <StatsCards />
  </div>
</template>

<script setup>
import { onMounted, onUnmounted } from 'vue'
import { useAlertsStore } from '@/store/alerts'
import StatsCards from '@/components/StatsCards.vue'

const alertsStore = useAlertsStore()

// Polling for live data
let pollingInterval = null

onMounted(() => {
  alertsStore.fetchAlerts()
  pollingInterval = setInterval(() => {
    alertsStore.fetchAlerts()
  }, 5000)
})

onUnmounted(() => {
  if (pollingInterval) {
    clearInterval(pollingInterval)
  }
})
</script>

<style scoped>
.analytics {
  animation: fadeIn 0.3s ease-in;
}

@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(10px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}
</style>
