// src/app/components/stats-cards/stats-cards.component.ts
import { Component, OnInit, OnDestroy, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Subscription } from 'rxjs';
import { AlertsStoreService } from '../../services/alerts-store.service';
import { StatusCounts, Alert } from '../../models/alert.model';

@Component({
  selector: 'app-stats-cards',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './stats-cards.component.html',
  styleUrls: ['./stats-cards.component.css']
})
export class StatsCardsComponent implements OnInit, OnDestroy {
  @Input() mode: 'dashboard' | 'analytics' = 'dashboard';

  statusCounts: StatusCounts = {
    all: 0,
    pending_approval: 0,
    in_progress: 0,
    resolved: 0,
    failed: 0
  };

  // Analytics-specific stats
  uniqueSourcesCount = 0;
  uniqueAgentsCount = 0;
  resolutionRate = 0;
  resolutionLabel = '0 of 0 alerts resolved';
  sourceList: string[] = [];
  agentList: string[] = [];

  private subscription = new Subscription();

  constructor(private alertsStore: AlertsStoreService) {}

  ngOnInit(): void {
    this.subscription.add(
      this.alertsStore.statusCounts$.subscribe(counts => {
        this.statusCounts = counts;
      })
    );

    if (this.mode === 'analytics') {
      this.subscription.add(
        this.alertsStore.alerts$.subscribe(alerts => {
          this.computeAnalyticsStats(alerts);
        })
      );
    }
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  private computeAnalyticsStats(alerts: Alert[]): void {
    if (!alerts.length) {
      this.uniqueSourcesCount = 0;
      this.uniqueAgentsCount = 0;
      this.resolutionRate = 0;
      this.resolutionLabel = '0 of 0 alerts resolved';
      this.sourceList = [];
      this.agentList = [];
      return;
    }

    // Unique Sources
    const sources = new Set<string>();
    alerts.forEach(a => sources.add(a.source || 'Unknown'));
    this.uniqueSourcesCount = sources.size;
    this.sourceList = Array.from(sources);

    // Unique Agents
    const agents = new Set<string>();
    alerts.forEach(a => {
      if (a.agentName) agents.add(a.agentName);
    });
    this.uniqueAgentsCount = agents.size;
    this.agentList = Array.from(agents);

    // Resolution Rate
    const total = alerts.length;
    const resolved = alerts.filter(a => (a.status || '').toLowerCase() === 'resolved').length;
    this.resolutionRate = total > 0 ? Math.round((resolved / total) * 100) : 0;
    this.resolutionLabel = `${resolved} of ${total} alerts resolved`;
  }
}

<!-- Default Cards (shown in both dashboard and analytics) -->
<div class="row g-3 mb-4">
  <div class="col-md-4">
    <div class="card stat-card border-0 shadow-sm">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <p class="text-muted mb-1 small">Total Alerts</p>
            <h3 class="mb-0">{{ statusCounts.all }}</h3>
          </div>
          <div class="stat-icon" style="background-color: rgba(21, 101, 192, 0.1); color: #6085b1;">
            <i class="bi bi-exclamation-triangle-fill"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card stat-card border-0 shadow-sm">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <p class="text-muted mb-1 small">In Progress</p>
            <h3 class="mb-0">{{ statusCounts.in_progress }}</h3>
          </div>
          <div class="stat-icon" style="background-color: rgba(21, 101, 192, 0.1); color: #346ba9;">
            <i class="bi bi-arrow-repeat"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="card stat-card border-0 shadow-sm">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <p class="text-muted mb-1 small">Resolved</p>
            <h3 class="mb-0">{{ statusCounts.resolved }}</h3>
          </div>
          <div class="stat-icon" style="background-color: rgba(46, 125, 50, 0.1); color: #7aa97d;">
            <i class="bi bi-check-circle-fill"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Analytics-only Cards: Sources, Agents, Resolution Rate -->
<div *ngIf="mode === 'analytics'" class="row g-3 mb-4">

  <!-- Sources -->
  <div class="col-md-4">
    <div class="card stat-card border-0 shadow-sm">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <p class="text-muted mb-1 small">Sources</p>
            <h3 class="mb-0">{{ uniqueSourcesCount }}</h3>
          </div>
          <div class="stat-icon" style="background-color: rgba(0, 150, 136, 0.1); color: #6085b1;">
            <i class="bi bi-diagram-3-fill"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Agents -->
  <div class="col-md-4">
    <div class="card stat-card border-0 shadow-sm">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <p class="text-muted mb-1 small">Agents</p>
            <h3 class="mb-0">{{ uniqueAgentsCount }}</h3>
          </div>
          <div class="stat-icon" style="background-color: rgba(156, 39, 176, 0.1); color: #346ba9;">
            <i class="bi bi-robot"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Resolution Rate -->
  <div class="col-md-4">
    <div class="card stat-card border-0 shadow-sm">
      <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
          <div>
            <p class="text-muted mb-1 small">Resolution Rate</p>
            <h3 class="mb-0">{{ resolutionRate }}%</h3>
          </div>
          <div class="stat-icon" style="background-color: rgba(46, 125, 50, 0.1); color: #009688;">
            <i class="bi bi-graph-up-arrow"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

// src/components/StatsCards.vue
<template>
  <div class="row g-3 mb-4">
    <div class="col-md-3">
      <div class="card stat-card border-0 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <p class="text-muted mb-1 small">Total Alerts</p>
              <h3 class="mb-0">{{ statusCounts.all }}</h3>
            </div>
            <div class="stat-icon bg-primary bg-opacity-10 text-primary">
              <i class="bi bi-exclamation-triangle-fill"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card stat-card border-0 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <p class="text-muted mb-1 small">Pending Approval</p>
              <h3 class="mb-0">{{ statusCounts.pending_approval }}</h3>
            </div>
            <div class="stat-icon bg-warning bg-opacity-10 text-warning">
              <i class="bi bi-clock-fill"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card stat-card border-0 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <p class="text-muted mb-1 small">In Progress</p>
              <h3 class="mb-0">{{ statusCounts.in_progress }}</h3>
            </div>
            <div class="stat-icon bg-info bg-opacity-10 text-info">
              <i class="bi bi-arrow-repeat"></i>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-3">
      <div class="card stat-card border-0 shadow-sm">
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <p class="text-muted mb-1 small">Resolved</p>
              <h3 class="mb-0">{{ statusCounts.resolved }}</h3>
            </div>
            <div class="stat-icon bg-success bg-opacity-10 text-success">
              <i class="bi bi-check-circle-fill"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useAlertsStore } from '@/store/alerts'

const alertsStore = useAlertsStore()

const statusCounts = computed(() => alertsStore.statusCounts)
</script>

<style scoped>
.stat-card {
  transition: transform 0.2s ease, box-shadow 0.2s ease;
}

.stat-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !important;
}

.stat-icon {
  width: 50px;
  height: 50px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1.5rem;
}
</style>
